### ISSUE TITLE
Discuss shebang when talking about file permissions in intermediate shell lesson.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/bc#265]

**Comment by gvwilson** [comment]
@ChristinaLK move this to the new shell lesson? Or close?

**Comment by ChristinaLK** [comment]
shell-extras?  or shell-novice?

**Comment by gvwilson** [comment]
shell-extras, I think?

On 2016-01-12 1:08 PM, Christina Koch wrote:
>
> shell-extras? or shell-novice?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/bc/issues/265#issuecomment-171054919>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by ChristinaLK** [comment]
yep - I"ll add an issue to add it to the permissions section
