### ISSUE TITLE
Domain-specific bioinformatics example

### ISSUE THREAD

**Issue by rbeagrie** [swcarpentry/bc#532]
A couple of people have said over the past month or so that a domain specific example that involves handling next-generation sequencing data would be a very useful thing to have - so it seemed like a good project for the [July sprints](https://etherpad.mozilla.org/swc-sprint-2014) next month.

I'm starting with the assumption that this will be a 1-2 hour exercise to sit right at the end of a SWC bootcamp. Since the people who are interested seem to be quite diverse, I would really appreciate it if people could leave some comments as to what might be most useful to them. This would really help us focus down on the right direction to be working in come July.

Specifically, if you would be interested in teaching with a domain specific example, it would be great if you could let us know:

1) Who would your target audience be, beginners, intermediates or something else?
2) Are there any tools you would like to be covered (I'm thinking bedtools, SAMtools, HTSeq, DE-seq etc.)
3) Should we aim more towards giving learners something they can do right now (e.g. making a bigwig file and uploading it to UCSC) or something that showcases the things they will be able to do with a bit more independent study (e.g. RNA-seq analysis)
4) How much should we try to tie in with the relevant set of language lessons, and which language? For example, should this be something that learners can follow having covered only the concepts in novice R, or intermediate python etc?
5) Are there any other parts of the core Software Carpentry curriculum we can be trying to reinforce (e.g. SQL)

If you have any other comments/thoughts/opinions please let us know!

**Comment by gvwilson** [comment]
Data Carpentry is doing this.
