### ISSUE TITLE
Can we add some simple tests to the software installation instructions?

### ISSUE THREAD

**Issue by DamienIrving** [swcarpentry/bc#647]
The default software installation instructions tell students where to go to get the relevant package installer for Anaconda, Git Bash, etc, but not how to test whether they have successfully installed that software. I'm wondering if our instructions should include a quick test for success? For git this might be, can you run `git --version`?

**Comment by r-gaia-cs** [comment]
@wking Can we close this?

**Comment by wking** [comment]
On Sat, Apr 11, 2015 at 05:08:51PM -0700, Raniere Silva wrote:
> @wking Can we close this?

Sure.  We still don't check 'git init', but I've pulled that out into
wking/swc-setup-installation-test#5.
