### ISSUE TITLE
Git remotes behind firewall and using a network drive

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/bc#744]
@iglpdc and I figured out how to teach git at the federal reserve by using the user's mapped drive as a git remote

thanks @gvwilson for forwarding @wking's response that started my google-fu.  I successfully (it worked!) taught it to the class, and was wondering should I write this up for other instructors?

If not for the students who attended so that they have a reference we can send them.

tldr; `git clone --bare my_repo my_repo.git` now every time there is a local push, you have to pull from the server

**Comment by gvwilson** [comment]
Replaced by https://github.com/swcarpentry/git-novice/issues/224
