### ISSUE TITLE
Diagrams for pipes and redirects

### ISSUE THREAD

**Issue by jpallen** [swcarpentry/bc#817]
I think that the concept of pipes and redirects can be explained well in diagram form. I was thinking about creating some diagrams along the lines of the image below (apologies for the quality, I couldn't get SVG -> PNG to work very well). I put these together quickly and they're quite rough since I thought it was best to gather some feedback first. Thoughts?

![redirects-and-pipes](https://cloud.githubusercontent.com/assets/31305/4780865/f1027736-5c7b-11e4-9edc-a315226eb984.png)

**Comment by gvwilson** [comment]
Replaced by https://github.com/swcarpentry/shell-novice/issues/435
