### ISSUE TITLE
Extract history of intermediate Python lesson

### ISSUE THREAD

**Issue by aaren** [swcarpentry/bc#882]
Work in progress: https://github.com/aaren/swc-intermediate-python/

- [x] extract novice/python history
- [x] append python/novice history

**Comment by kynan** [comment]
@aaren Would it make sense to transfer this to the swcarpentry organisation to make it easier for others to contribute?

**Comment by aaren** [comment]
> @aaren Would it make sense to transfer this to the swcarpentry organisation to make it easier for others to contribute?

@kynan yes I think so. It still needs someone else to sign off on the history extraction though (i.e. to look at aaren/swc-intermediate-python and check that I got all the history from bc). Can you do that?

Is `swcarpentry/python-intermediate-mosquitos` the right name?

@gvwilson thoughts on this? Is there any reason not to transfer the intermediate lessons to the lesson-template now? Applies to #929 as well.

**Comment by gvwilson** [comment]
+1 to transferring to the new lesson template - thanks!

**Comment by ethanwhite** [comment]
History extraction looks good to me. +1 for finishing up the move.

**Comment by aaren** [comment]
ok. I'll go ahead when I've some free time.

**Comment by kynan** [comment]
History extraction looks sane to me too. Go ahead and we'll fix any outstanding issues after the transfer.

**Comment by aaren** [comment]
See https://github.com/aaren/swc-intermediate-python

I've done the fiddling around on master. The raw extracted history is still on `intermediate-python-history`.

**Comment by aaren** [comment]
@gvwilson when you've got a minute can you create swcarpentry/python-intermediate-mosquitos?

**Comment by gvwilson** [comment]
https://github.com/swcarpentry/python-intermediate-mosquitoes (note: 
Wikipedia says the plural is spelled "es" on the end, so I went with that).

**Comment by kynan** [comment]
Thanks, @gvwilson!

**Comment by kynan** [comment]
@gvwilson Actually, wouldn't it be better for @aaren to *transfer* the repository? That would mean that issues like this one etc. are kept.

**Comment by aaren** [comment]
@gvwilson I think you need to change the permissions - I can't push.

@kynan not sure exactly what you mean - is that a github thing?

**Comment by aaren** [comment]
@kynan I see now, in the repo settings.

**Comment by aaren** [comment]
@kynan we could do a transfer, but I'm not sure there would be any benefit seeing as I have zero issues or PRs on my repo.

**Comment by kynan** [comment]
Yes, that's right. However @gvwilson would need to delete the repo he has created again (you obviously can't have the same name).

**Comment by kynan** [comment]
@aaren Ah yes indeed, this issue is against the bc repo! In that case I don't really mind. Either way we'd need push access though...

**Comment by gvwilson** [comment]
And our experience of transferring repositories has been less than 
stellar...

**Comment by gvwilson** [comment]
Whoops - my mistake.  I've added the 'developers' team, so you should 
have push now.

**Comment by kynan** [comment]
Fab . @aaren are you OK to push it up? Otherwise I'm happy to do it.

**Comment by aaren** [comment]
pushed to https://github.com/swcarpentry/python-intermediate-mosquitoes!

I wasn't sure about the spelling of mozzies. I was imagining them having toes and that seemed odd, but now that'll be how I remember the spelling :)

**Comment by kynan** [comment]
@aaren I would have done a force push, but nvm.
