### ISSUE TITLE
Extract history of novice Mercurial lesson

### ISSUE THREAD

**Issue by twitwi** [swcarpentry/bc#885]
Following the other splits, I used:

    git filter-branch --subdirectory-filter novice/hg --prune-empty

It's there for now: https://github.com/twitwi/swc-novice-hg

Note: the first commit about mercurial is (and was) the copy from the git lesson, but the history is from the git lessons is (and was) not attached to the mercurial lesson.

**Comment by wking** [comment]
Can this be closed now that we have
https://github.com/swcarpentry/hg-novice?
