### ISSUE TITLE
instr function not available in SQLite 3.7.13 and older

### ISSUE THREAD

**Issue by danabauer** [swcarpentry/bc#925]
One of the challenge questions in SQL lesson 04-calc requires students to use the instr function. This function wasn't introduced until 3.7.15 and it's likely students using the pre-installed version of SQLite on Mac OS X and Linux will have older versions. Perhaps add a note in the lesson? Or prompt students to check their version of SQLite in the installation instructions and upgrade?

**Comment by r-gaia-cs** [comment]
@danabauer Thanks very much for report this. Could you copy and past this issue into https://github.com/swcarpentry/sql-novice-survey and after that close this one?

**Comment by danabauer** [comment]
Thanks. I moved it here: https://github.com/swcarpentry/sql-novice-survey/issues/13
