### ISSUE TITLE
Instructor's Guide ... General Advice ... Teaching Notes ... Duplication

### ISSUE THREAD

**Issue by statkclee** [swcarpentry/bc#926]
When I translate teaching notes, I found one duplication... 
----------------------------------------------------------------------------------------
For workshops that extend over more than two days (e.g., four afternoons spread over two weeks), it's a good idea to email the learners at the end of each day with a summary of what was taught (with links to the relevant online notes). This allows absent learners to catch up before the next session, and is also a great opporunity to present the lessons of the day in the context of the entire workshop.
-----------------------------------------------------------------------------------------

**Comment by r-gaia-cs** [comment]
@statkclee Thanks for the report. I'm closing this due #927. If you need to add one comment please do it on #927 and if you could review #927 will be great.
